// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1DdehpDI12ycX5NEwdd80QL93sALGcWg',
    appId: '1:165986621597:web:ecf674cbcf63c32e5a9c74',
    messagingSenderId: '165986621597',
    projectId: 'fir-example-afd4d',
    authDomain: 'fir-example-afd4d.firebaseapp.com',
    storageBucket: 'fir-example-afd4d.appspot.com',
    measurementId: 'G-DK1BV0BWK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFTWsjGTu2r4uwZRwpvp71AM_ii28vcI',
    appId: '1:165986621597:android:c400444f947bfe655a9c74',
    messagingSenderId: '165986621597',
    projectId: 'fir-example-afd4d',
    storageBucket: 'fir-example-afd4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZZj1ZyZQeICGTSjSX9r8x9_FEOT8lRo',
    appId: '1:165986621597:ios:4ce13a211f2469955a9c74',
    messagingSenderId: '165986621597',
    projectId: 'fir-example-afd4d',
    storageBucket: 'fir-example-afd4d.appspot.com',
    androidClientId: '165986621597-fgd7ssr2mv8uh02rdrtmrgg3t07g2v63.apps.googleusercontent.com',
    iosClientId: '165986621597-uh0asp7gskdgd6ie5u0k0keqnise3k93.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbZZj1ZyZQeICGTSjSX9r8x9_FEOT8lRo',
    appId: '1:165986621597:ios:4ce13a211f2469955a9c74',
    messagingSenderId: '165986621597',
    projectId: 'fir-example-afd4d',
    storageBucket: 'fir-example-afd4d.appspot.com',
    androidClientId: '165986621597-fgd7ssr2mv8uh02rdrtmrgg3t07g2v63.apps.googleusercontent.com',
    iosClientId: '165986621597-uh0asp7gskdgd6ie5u0k0keqnise3k93.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
